# Generated by Django 5.2.2 on 2025-06-04 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistanceBasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('upto_km', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_prices', to='Billing.pricingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='DistanceAdditionalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_prices', to='Billing.pricingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Billing.pricingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='TimeMultiplierFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_minutes', models.IntegerField()),
                ('max_minutes', models.IntegerField()),
                ('multiplier', models.FloatField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_multipliers', to='Billing.pricingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_minutes', models.IntegerField()),
                ('after_minutes', models.IntegerField()),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_charge', to='Billing.pricingconfig')),
            ],
        ),
    ]
